#!/bin/bash
#date +%Y-%m-%d_%H_%M_%S
#ffmpeg -f x11grab -s 3840x1200 -i :0.0 -c:v libx264 -preset medium -crf 0  $(date +%Y-%m-%d_%H_%M_%S).mkv
ffmpeg -video_size 3840x1200 -framerate 30 -f x11grab -i :1.0 -c:v libx264 -qp 0 -preset ultrafast $(date +%Y-%m-%d_%H_%M_%S)..mkv